routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@loadUser')->name('user');
Route::post('/admin/store', 'Admin\ResultsController@store');
Route::get('/user/attendance', 'AttendanceController@update')->name('userAttendance');
Route::get('/user/absence', 'AbsenceController@update')->name('userAbsence');

//Rules
Route::get('/rules', 'RulesController@index')->name('rules');

//scores from everyone
Route::get('/scores', 'Score\ScoreController@index')->name('scores');

//Violations


Route::resource('violation', 'ViolationController')->only('store');
Route::get('violation', 'ViolationController@index')->name('violation-index');




//every route only available for "admin"
Route::group(['middleware' => ['check-admin']], function ()
{
    //Admin Tournament routes
    Route::model('admintournament','App\Models\Tournament');
    Route::resource('admintournament', 'Admin\TournamentController');

    //Admin Round routes
    Route::model('admintournament.round','App\Models\Rounds');
    Route::model('admintournament.round','App\Models\Tournament');
    Route::resource('admintournament.round', 'Admin\RoundsController');

    //Admin rules routes
    Route::get('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules/remove', 'Admin\RulesController@delete')->name('deleteRule');
    Route::post('admin/rules/edit', 'Admin\RulesController@edit')->name('editRule');
    Route::post('admin/rules/save', 'Admin\RulesController@update')->name('saveRule');
    Route::post('admin/rules/add', 'Admin\RulesController@create')->name('addRule');

    //Admin add result routes
    Route::post('/admintournament/{tournament}/store/{round}', 'Admin\ResultsController@store')->name('store-result');
    Route::post('/admintournament/{tournament}/show', 'Admin\ResultsController@show')->name('show-result');
    Route::get('/admintournament/{tournament}/destroy/{id}', 'Admin\ResultsController@destroy')->name('delete-result');
    Route::get('/admin/final_round', 'Score\FinalRoundController@index')->name('finalRound');
    Route::get('/admin/final_round/players', 'Score\FinalRoundController@show')->name('finalRound-players');
    Route::post('/admin/final_round/win', 'Score\FinalRoundController@store')->name('finalRound-win');


    Route::get('/admintournament/{tournament}/result', 'Admin\ResultsController@index')->name('index-result');


    //Admin route for starting clock
    Route::get('/admin/clock', 'Admin\ClockController@index')->name('index-clock');
    Route::get('/admin/clock/view', 'Admin\ClockController@show')->name('show-clock');
    Route::get('/admin/clock/start-clock', 'Admin\ClockController@update')->name('index-start-clock');
    Route::get('/admin/clock/stop-clock', 'Admin\ClockController@destroy')->name('index-start-clock');

    //admin pages
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');
    Route::get('/admin/users', 'Admin\UsersController@index')->name('adminUsers');
    Route::post('/admin/users/remove', 'Admin\UsersController@delete')->name('deleteUser');
    Route::get('/admin/users/update{id}', 'Admin\UsersController@update')->name('updateUser');

    //Attendants routes
    Route::get('/admin/attendants', 'AttendantsController@index')->name('attendants');
    Route::post('/admin/attendants/update', 'AttendantsController@update')->name('attendantsUpdate');


});

app/Models/Violations.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Rules;
use App\Models\Rounds;

class Violations extends Model
{
    /**
     * Get the user from the violation.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the rule from the violation.
     */
    public function rules()
    {
        return $this->belongsTo(Rules::class);
    }

    /**
     * Get the round from the violation.
     */
    public function rounds()
    {
        return $this->belongsTo(Rounds::class);
    }



}

app/Http/Controllers/ViolationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateViolationRequest;
use App\Models\Rounds;
use App\Models\Rules;
use App\Models\User;
use App\Models\Violations;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class ViolationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $allUsers = User::all();
        $allRules = Rules::all();
        $allRounds = Rounds::all();
        $violation = Violations::all();
//        return view('violation.index', compact('violation'));
        return response(view('violation.index', compact('violation','allUsers', 'allRules', 'allRounds')));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $selectedUser = $request->input('violation_user');
        $selectedRound = $request->input('violation_round');
        $selectedRule = $request->input('violation_rule');


        $violation = new Violations;
        $violation->users_id = $selectedUser;
        $violation->rounds_id = $selectedRound;
        $violation->rules_id = $selectedRule;

        $violation->save();


        return redirect()->route('violation-index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Violation  $violation
     * @return Response
     */
    public function show(Violation $violation)
    {
        echo "<pre>";
        print_r("show");
        exit;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Violation  $violation
     * @return Response
     */
    public function edit(Violation $violation)
    {
        echo "<pre>";
        print_r("edit");
        exit;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Violations  $violation
     * @return Response
     */
    public function update(Request $request, Violations $violations)
    {
        echo "<pre>";
        print_r("update");
        exit;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Violation  $violation
     * @return Response
     */
    public function destroy(Violation $violation)
    {
        echo "<pre>";
        print_r("destroy");
        exit;
    }
}

resources/views/violation/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container mt-4">

        <div class="card-header bg-dark text-light row mt-5 rounded-top">
            Overtreding melden
        </div>
        <div class="card-body bg-light row mb-3 d-flex justify-content-center">
            <div class="col-6">
                {{--                <a href="{{route('violationStore')}}">klik hier </a>--}}
                <form action="{{ route('violation.store') }}" method="POST">
                    @csrf
                    <label for="title">
                        Wie heeft de overtreding gemaakt?
                    </label>
                    <select id="title" class="form-control form-control-sm mb-2 small" name="violation_user" required>
                        @foreach($allUsers as $user)
                            <option value="{{$user->id}}">{{$user->name}}</option>
                        @endforeach
                    </select>
                    <label for="description">
                        Welke ronde is de overtreding gemaakt?
                    </label>
                        <select id="description" class="form-control form-control-sm mb-2 small" name="violation_round" required>
                        @foreach($allRounds as $round)
                            <option value="{{$round->id}}">{{$round->round_nr}}</option>
                        @endforeach
                    </select>
                    <label for="rounds">
                        Welke regel is volgens jou overtreden?
                    </label>
                    <select id="rounds" class="form-control form-control-sm mb-2 small" name="violation_rule">
                        @foreach($allRules as $rule)
                            <option value="{{$rule->id}}">{{$rule->description}}</option>
                        @endforeach
                    </select>

                    <button type="submit" class="btn btn-info">Overtreding melden</button>
                </form>
            </div>
        </div>

                <div class="card-header bg-dark text-light row mt-5 rounded-top">
                    Overtredingen:
                </div>

                @foreach($violation as $vio)
                    <div class="card-body bg-light mb-3 row">
                        <div class="row">
                            <div class="col-12">
                                Violation id: {{ $vio->id }},
                                Wie heeft de overtreding gemaakt: {{ $vio->users_id }},
                                In welke ronde gebeurde het : {{ $vio->rounds_id }},
                                Overtreden regel : {{ $vio->rules_id }},

                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
    </div>


@endsection