routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@loadUser')->name('user');
Route::post('/admin/store', 'Admin\ResultsController@store');
Route::get('/user/attendance', 'AttendanceController@update')->name('userAttendance');
Route::get('/user/absence', 'AbsenceController@update')->name('userAbsence');

//Rules
Route::get('/rules', 'RulesController@index')->name('rules');

//scores from everyone
Route::get('/scores', 'Score\ScoreController@index')->name('scores');

//Violations


Route::resource('violation', 'ViolationController')->only('store');
Route::get('violation', 'ViolationController@index')->name('violation-index');




//every route only available for "admin"
Route::group(['middleware' => ['check-admin']], function ()
{
    //Admin Tournament routes
    Route::model('admintournament','App\Models\Tournament');
    Route::resource('admintournament', 'Admin\TournamentController');

    //Admin Round routes
    Route::model('admintournament.round','App\Models\Rounds');
    Route::model('admintournament.round','App\Models\Tournament');
    Route::resource('admintournament.round', 'Admin\RoundsController');

    //Admin rules routes
    Route::get('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules/remove', 'Admin\RulesController@delete')->name('deleteRule');
    Route::post('admin/rules/edit', 'Admin\RulesController@edit')->name('editRule');
    Route::post('admin/rules/save', 'Admin\RulesController@update')->name('saveRule');
    Route::post('admin/rules/add', 'Admin\RulesController@create')->name('addRule');

    //Admin add result routes
    Route::post('/admintournament/{tournament}/store/{round}', 'Admin\ResultsController@store')->name('store-result');
    Route::post('/admintournament/{tournament}/show', 'Admin\ResultsController@show')->name('show-result');
    Route::get('/admintournament/{tournament}/destroy/{id}', 'Admin\ResultsController@destroy')->name('delete-result');
    Route::get('/admin/final_round', 'Score\FinalRoundController@index')->name('finalRound');
    Route::get('/admin/final_round/players', 'Score\FinalRoundController@show')->name('finalRound-players');
    Route::post('/admin/final_round/win', 'Score\FinalRoundController@store')->name('finalRound-win');


    Route::get('/admintournament/{tournament}/result', 'Admin\ResultsController@index')->name('index-result');


    //Admin route for starting clock
    Route::get('/admin/clock', 'Admin\ClockController@index')->name('index-clock');
    Route::get('/admin/clock/view', 'Admin\ClockController@show')->name('show-clock');
    Route::get('/admin/clock/start-clock', 'Admin\ClockController@update')->name('index-start-clock');
    Route::get('/admin/clock/stop-clock', 'Admin\ClockController@destroy')->name('index-start-clock');

    //admin pages
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');
    Route::get('/admin/users', 'Admin\UsersController@index')->name('adminUsers');
    Route::post('/admin/users/remove', 'Admin\UsersController@delete')->name('deleteUser');
    Route::get('/admin/users/update{id}', 'Admin\UsersController@update')->name('updateUser');

    //Attendants routes
    Route::get('/admin/attendants', 'AttendantsController@index')->name('attendants');
    Route::post('/admin/attendants/update', 'AttendantsController@update')->name('attendantsUpdate');


});

app/Models/Tournament.php
<?php

namespace App\Models;

use App\Models\Rounds;
use App\Models\User;
use App\Models\TournamentUser;
use Illuminate\Database\Eloquent\Model;

class Tournament extends Model
{
    public function user()
    {
        return $this->belongsToMany(User::class)
            ->using(TournamentUser::class);
    }

    public function round()
    {
        return $this->hasMany(Rounds::class);
    }
}

app/Http/Controllers/Admin/TournamentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Rounds;
use App\Models\Rules;
use App\Models\Tournament;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\CreateTournamentRequest;

class TournamentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tournaments = Tournament::all();
        return response(view('admin.tournament.index', compact('tournaments')));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CreateTournamentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTournamentRequest $request)
    {

        $data = $request->validated();

        $tournament = new Tournament;
        $tournament->title = $data['title'];
        $tournament->description = $data['description'];
        $tournament->active = $data['active'];
        $tournament->rounds = $data['rounds'];
        $tournament->open = 0;

        $tournament->save();

        return response(redirect('admintournament'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tournament $tournament
     * @return \Illuminate\Http\Response
     */
    public function show(Tournament $tournament)
    {
        $rounds = $tournament->round;

        return response(view('admin.tournament.show', compact('tournament', 'rounds')));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function edit(Tournament $tournament)
    {
        return response(view('admin.tournament.edit', compact('tournament')));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CreateTournamentRequest  $request
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function update(CreateTournamentRequest $request, Tournament $tournament)
    {
        $data = $request->validated();

        $tournament->title = $data['title'];
        $tournament->description = $data['description'];
        $tournament->active = $data['active'];
        $tournament->open = $data['open'];
        $tournament->rounds = $data['rounds'];

        $tournament->update();

        return redirect(route('admintournament.show', $tournament));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tournament $tournament)
    {
        $tournament->delete();

        return response(redirect('admintournament'));
    }
}

app/Http/Controllers/TournamentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tournament;
use Illuminate\Http\Request;

class TournamentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        return response(view());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function show(Tournament $tournament)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function edit(Tournament $tournament)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tournament $tournament)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tournament  $tournament
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tournament $tournament)
    {
        //
    }
}

resources/views/admin/tournament/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container mt-4">

        <div class="card-header bg-dark text-light row mt-5 rounded-top">
            Toernooi veranderen
        </div>
        <div class="card-body bg-light row mb-3 d-flex justify-content-center">
            <div class="col-6">
                <form action="{{ route('admintournament.update', $tournament) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    <label for="title">
                        Titel
                    </label>
                    <input class="form-control mb-2" name="title" id="title" type="text" value="{{$tournament->title}}">

                    <label for="description">
                        Beschrijving
                    </label>
                    <textarea class="form-control mb-2" name="description" id="description"
                              type="text" rows="6">{{$tournament->description}}</textarea>

                    <div class="custom-control custom-checkbox mb-2">
                        <input hidden name="active" value="0">

                        <input class="custom-control-input" type="checkbox" value="1" name="active" id="active"
                               @if($tournament->active == 1)
                               checked
                            @endif
                        >
                        <label class="custom-control-label" for="active">Actief (zet uit als het toernooi voorbij is)</label>
                    </div>

                    <div class="custom-control custom-checkbox mb-2">
                        <input hidden name="open" value="0">

                        <input class="custom-control-input" type="checkbox" value="1" name="open" id="open"
                               @if($tournament->open == 1)
                               checked
                            @endif
                        >
                        <label class="custom-control-label" for="open">Open voor registratie (zichtbaar voor spelers)</label>
                    </div>

                    <label for="rounds">
                        Aantal rondes
                    </label>
                    <input class="form-control mb-2" name="rounds" id="rounds" type="number"
                           value="{{$tournament->rounds}}">

                    <button type="submit" class="btn btn-info">Toernament updaten</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/tournament/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container mt-4">

        <div class="card-header bg-dark text-light row mt-5 rounded-top">
            Toernooi Toevoegen
        </div>
        <div class="card-body bg-light row mb-3 d-flex justify-content-center">
            <div class="col-6">
            <form action="{{ route('admintournament.store') }}" method="POST">
                @csrf
                <label for="title">
                    Titel
                </label>
                <input class="form-control mb-2" name="title" id="title" type="text">

                <label for="description">
                    Beschrijving
                </label>
                <textarea class="form-control mb-2" name="description" id="description" type="text" rows="6"></textarea>

                <div class="custom-control custom-switch mb-2">
                    <input hidden name="active" value="0">
                    <input class="custom-control-input" name="active" id="active" type="checkbox" value="1">
                    <label class="custom-control-label" for="active">Actief</label>
                </div>

                <label for="rounds">
                    Aantal rondes
                </label>
                <input class="form-control mb-2" name="rounds" id="rounds" type="number">

                <button type="submit" class="btn btn-info">Toernament toevoegen</button>
            </form>
            </div>
        </div>

        <div class="card-header bg-dark text-light row">
            Toernooi:
        </div>

        @foreach($tournaments as $tournament)
            <div class="card-body bg-light row">
                <div class="col-7">
                    <div class="row">
                        {{ $tournament->title }}
                    </div>
                </div>

                <a href="{{ route('admintournament.show', $tournament) }}">
                    <button class="btn btn-info ml-2 col text-light">Meer informatie</button>
                </a>


            </div>
        @endforeach


    </div>


@endsection

resources/views/admin/tournament/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <h1>{{$tournament->title}}</h1>
                        <p>{{$tournament->description}}</p>
                        <p>Actief: {{$tournament->active}}</p>
                        <p>Open: {{$tournament->open}}</p>
                        <p>Aantal rondes: {{$tournament->rounds}}</p>

                        <form class="col-2 m-3" action="{{ route('admintournament.edit', $tournament) }}" method="GET">
                            <button class="btn btn-info ml-2 col text-light">
                                Verander toernooi
                            </button>
                        </form>

                        <form class="col-2 m-3" action="{{ route('index-result', $tournament) }}" method="GET">
                            <button class="btn btn-info ml-2 col text-light">Scores invoeren</button>
                        </form>

                        <form class="col-2 m-3" action="{{ route('admintournament.destroy', $tournament) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-danger ml-2 col">Verwijder toernooi</button>
                        </form>


                    </div>
                </div>

                <div class="card mb-3">
                    <div class="card-body">
                        <form action="{{ route('admintournament.round.store', $tournament) }}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-info">Nieuwe ronde aanmaken</button>
                        </form>

                        @foreach($rounds as $round)
                            <h1>Ronde {{ $round->round_nr }}</h1>
                            <p>Ronde start om: {{ $round->start_time }}</p>
                            <p>Ronde stopt om: {{ $round->stop_time }}</p>

                            <form class="col-2 m-3" action="{{ route('admintournament.round.show', [$tournament, $round]) }}" method="GET">
                                <button class="btn btn-info ml-2">
                                    Scores inzien
                                </button>
                            </form>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection