routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@loadUser')->name('user');
Route::post('/admin/store', 'Admin\ResultsController@store');
Route::get('/user/attendance', 'AttendanceController@update')->name('userAttendance');
Route::get('/user/absence', 'AbsenceController@update')->name('userAbsence');

//Rules
Route::get('/rules', 'RulesController@index')->name('rules');

//scores from everyone
Route::get('/scores', 'Score\ScoreController@index')->name('scores');

//Violations


Route::resource('violation', 'ViolationController')->only('store');
Route::get('violation', 'ViolationController@index')->name('violation-index');




//every route only available for "admin"
Route::group(['middleware' => ['check-admin']], function ()
{
    //Admin Tournament routes
    Route::model('admintournament','App\Models\Tournament');
    Route::resource('admintournament', 'Admin\TournamentController');

    //Admin Round routes
    Route::model('admintournament.round','App\Models\Rounds');
    Route::model('admintournament.round','App\Models\Tournament');
    Route::resource('admintournament.round', 'Admin\RoundsController');

    //Admin rules routes
    Route::get('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules', 'Admin\RulesController@index')->name('adminRules');
    Route::post('admin/rules/remove', 'Admin\RulesController@delete')->name('deleteRule');
    Route::post('admin/rules/edit', 'Admin\RulesController@edit')->name('editRule');
    Route::post('admin/rules/save', 'Admin\RulesController@update')->name('saveRule');
    Route::post('admin/rules/add', 'Admin\RulesController@create')->name('addRule');

    //Admin add result routes
    Route::post('/admintournament/{tournament}/store/{round}', 'Admin\ResultsController@store')->name('store-result');
    Route::post('/admintournament/{tournament}/show', 'Admin\ResultsController@show')->name('show-result');
    Route::get('/admintournament/{tournament}/destroy/{id}', 'Admin\ResultsController@destroy')->name('delete-result');
    Route::get('/admin/final_round', 'Score\FinalRoundController@index')->name('finalRound');
    Route::get('/admin/final_round/players', 'Score\FinalRoundController@show')->name('finalRound-players');
    Route::post('/admin/final_round/win', 'Score\FinalRoundController@store')->name('finalRound-win');


    Route::get('/admintournament/{tournament}/result', 'Admin\ResultsController@index')->name('index-result');


    //Admin route for starting clock
    Route::get('/admin/clock', 'Admin\ClockController@index')->name('index-clock');
    Route::get('/admin/clock/view', 'Admin\ClockController@show')->name('show-clock');
    Route::get('/admin/clock/start-clock', 'Admin\ClockController@update')->name('index-start-clock');
    Route::get('/admin/clock/stop-clock', 'Admin\ClockController@destroy')->name('index-start-clock');

    //admin pages
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');
    Route::get('/admin/users', 'Admin\UsersController@index')->name('adminUsers');
    Route::post('/admin/users/remove', 'Admin\UsersController@delete')->name('deleteUser');
    Route::get('/admin/users/update{id}', 'Admin\UsersController@update')->name('updateUser');

    //Attendants routes
    Route::get('/admin/attendants', 'AttendantsController@index')->name('attendants');
    Route::post('/admin/attendants/update', 'AttendantsController@update')->name('attendantsUpdate');


});

resources/views/admin/add_points.blade.php
@extends('layouts.app')

@section('head')
    <link rel="stylesheet" href="../css/add_points.css">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card mt-4">
                    <div class="card-header">
                        Vul hier de scores in van de spelers
                    </div>
                    <form class="m-4" method="POST" action="{{ route('show-result', $tournament) }}">
                        @csrf
                        <div class="form-group">
                            <label for="round">Selecteer de ronde</label>
                            <select name="round" id="round" class="selectpicker form-control"
                                    data-live-search="true">
                                @foreach($rounds as $round)
                                    <option value="{{$round->round_nr}}">Ronde {{$round->round_nr}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="tables">Selecteer de tafel</label>
                            <select name="table" id="tables" class="selectpicker form-control"
                                    data-live-search="true">
                                @foreach($tables as $table)
                                    <option value="{{$table->id}}">Tafel {{$table->id}}</option>
                                @endforeach
                            </select>
                        </div>

                        <input type="submit" class="btn btn-info" value="Zoeken">
                    </form>
                    <div class="container">
                        @if(isset($users))
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Naam</th>
                                    <th scope="col">Score</th>
                                </tr>
                                </thead>
                                <tbody>
                                <form action="{{route('store-result', [$tournament, $round])}}" method="POST">
                                    @csrf
                                    @foreach($users as $user)
                                        <tr>
                                            <th scope="row">{{$user->id}}</th>
                                            <td>{{$user->name}}</td>
                                            <td>
                                                <label>
                                                    <input value="{{ $user->score }}" placeholder="{{ $user->score }}" type="number" name="scores[{{$user->id}}]">
                                                </label>
                                            </td>
                                            <td><a href="{{ route('delete-result', [$user->id, $tournament]) }}" class="btn btn-danger">Verwijder</a></td>

                                                <td><a href="{{route('violation-index')}}" class="btn btn-warning">Te laat</a></td>

                                        </tr>
                                    @endforeach
                                    <tr>
                                        <td>
                                            <input class="btn btn-info" type="submit" value="Opslaan">
                                        </td>
                                    </tr>
                                </form>
                                </tbody>
                            </table>

                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/attendants.blade.php
@extends('layouts.app')

@section('content')

    <div class="text-center text-capitalize text-bold">
        <div class="container col-md-7 card mt-2">
        <div class="card-body row">
            <div class="col-12 text-center font-weight-bold te">
               Totaal Aantal Deelnemers: {{ count($attendants) }}
            </div>
        </div>

    </div>
        <br>
    <div class="container col-md-7 card">
        <div class="card-header row">
            <div class="col-4">
                Naam:
            </div>
            <div class="col-4">
                Email:
            </div>
            <div class="col-4">
                Gebruiker verwijderen
            </div>
        </div>
        @foreach($attendants as $attendant)
            <div class="card-body row">
                <div class="col-4">
                    {{$attendant->name}}
                </div>
                <div class="col-4">
                    {{$attendant->email}}
                </div>
                <div class="col-4">
                    <form action={{ route('deleteUser') }} method="POST">
                        @csrf
                        <button type="submit" name="id" value="{{ $attendant->id }}" class="btn btn-info">Gebruiker absent melden</button>
                    </form>
                </div>
            </div>
        @endforeach

    </div>
@endsection

resources/views/admin/clock.blade.php
@extends('layouts.app')
@section('head')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@endsection

@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <h1>Druk op de knop om ronde {{$all_round->id}} te starten</h1>
            </div>
            <div class="card-body">
                @if($started)
                    <div id="demo"></div>
                    <!-- start or stop the timer for that round -->
                    <a id="stop-round" class="btn btn-info" href="/admin/clock/stop-clock?round={{$all_round->id}}">Stop
                        ronde</a>
                @else
                    <a id="start-round" class="btn btn-info" href="/admin/clock/start-clock?round={{$all_round->id}}">Start
                        ronde</a>
                @endif
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script>
        var d1 = new Date(),
            d2 = new Date(d1);
        countDownDate = d2.setMinutes(d1.getMinutes() + 45);

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get today's date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Display the result in the element with id="demo"
            document.getElementById("demo").innerHTML = days + "d " + hours + "h "
                + minutes + "m " + seconds + "s ";

            // If the count down is finished, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "EXPIRED";
            }
        }, 1000);


    </script>
@endsection

resources/views/admin/edit_rules.blade.php
@extends('layouts.app')

@section('head')
    <link rel="stylesheet" href="css/homestyle.css">
@endsection

@section('content')

    <div class="container mt-4">

        <div class="card-header bg-dark text-light row">
            Regel:
        </div>
        <div class="card-body bg-light">
            <form action="{{ route('saveRule') }}" method="POST">
                @csrf
                <input type="text" name="descriptionNew" class="form-group form-control" value="{{ $rule }}">
                <button type="submit" name="description" value="{{ $rule }}" class="btn btn-info">Verander regel</button>
            </form>
        </div>



    </div>


@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-2">
        <div class="jumbotron">
            <p>Beheer toernamenten</p>
            <a href="{{ route('admintournament.index') }}">Klik hier</a>
        </div>
        <div class="jumbotron">
            <p>Gebruikers bekijken</p>
            <a href="{{route('adminUsers')}}">Klik hier</a>
        </div>
        <div class="jumbotron">
            <p>Deelnemers bekijken</p>
            <a href="{{ route('attendants') }}">Klik hier</a>
        </div>
        <div class="jumbotron">
            <p>Regels bekijken en aanpassen</p>
            <a href="{{ route('adminRules') }}">Klik hier</a>
        </div>
        <div class="jumbotron">
            <p>Klok</p>
            <a href="{{ route('index-clock') }}">Klik hier</a>
        </div>
        <div class="jumbotron">
            <p>Start laatste rondes</p>
            <a href="{{ route('finalRound') }}">Klik hier</a>
        </div>
    </div>

@endsection

resources/views/admin/round_clock.blade.php
@extends('layouts.app')



@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                Druk op de knop om het spel te starten
            </div>
            <div class="card-body">
                <form action="/admin/clock/view">
                    <label for="select-round">Selecteer de ronde</label>
                    <select id="select-round" name="round" class="form-control mb-2" onchange="this.form.submit()">
                        <option selected value="no">Kies een ronde...</option>
                        @foreach ($rounds as $round)
                            <option value="{{$round->id}}">{{$round->id}}</option>
                        @endforeach
                    </select>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')

@endsection

resources/views/admin/rules.blade.php
@extends('layouts.app')

@section('head')
    <link rel="stylesheet" href="css/homestyle.css">
@endsection


@section('content')

    <div class="container mt-4">

        <div class="card-header bg-dark text-light row">
            Regels:
        </div>

        @foreach($rules as $rule)
            <div class="card-body bg-light row">
                <div class="col-7"> {{ $rule->description }} </div>
                <form class="col-2" action={{ route('editRule') }} method="POST">
                    @csrf
                    <button type="submit" name="description" value="{{ $rule->description }}" class="btn btn-info ml-2 col text-light">Verander regel</button>
                </form>
                <form class="col-2" action={{ route('deleteRule') }} method="POST">
                    @csrf
                    <button type="submit" name="id" value="{{ $rule->id }}" class="btn btn-danger ml-2 col">Verwijder regel</button>
                </form>
            </div>
        @endforeach

        <div class="card-header bg-dark text-light row mt-5 rounded-top">
            Regel Toevoegen
        </div>
        <div class="card-body bg-light row">
        <form action="{{ route('addRule') }}" method="POST">
            @csrf
            <label class="col align-middle">
                <textarea class="form-group form-control col align-middle" placeholder="Regel" name="description"></textarea>
            </label>
            <button type="submit" class="btn btn-info">Regel toevoegen</button>
        </form>
        </div>
    </div>


@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('content')

<div class="text-center text-capitalize text-bold">

    <br>
</div>
<div class="container col-md-8 card">
    <div class="card-header row">
        <div class="col-3">
            Naam:
        </div>
        <div class="col-3">
            Email:
        </div>
        <div class="col-3">
            Gebruiker verwijderen
        </div>
        <div class="col-3">
            Gebruiker wijzigen
        </div>
    </div>
    @foreach($users as $user)

        <div class="card-body row">
            <div class="col-3">
            {{$user->name}}
            </div>
            <div class="col-3">
                {{$user->email}}
            </div>
            <div class="col-3">
                <form action={{ route('deleteUser') }} method="POST">
                        @csrf
                        <button type="submit" name="id" value="{{ $user->id }}" class="btn btn-danger">Verwijder Gebruiker</button>
                </form>

            </div>
            <div class="col-3">
                <a  href="{{route('updateUser',$user->id) }}" class="btn btn-info">Maak Admin</a>
            </div>
        </div>
    @endforeach

</div>
@endsection